
language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.1

matrix:
  fast_finish: true

before_install:
  # install PHP installation dependencies
  - sudo apt-get update > /dev/null
  - sudo apt-get install  > /dev/null
  - sudo apt-get install -y libxml2-dev  > /dev/null
  - sudo apt-get install -y libcurl4-openssl-dev  > /dev/null
  - sudo apt-get install -y libjpeg-dev  > /dev/null
  - sudo apt-get install -y libpng-dev  > /dev/null
  - sudo apt-get install -y libxpm-dev  > /dev/null
  - sudo apt-get install -y libmysqlclient-dev  > /dev/null
  - sudo apt-get install -y libpq-dev  > /dev/null
  - sudo apt-get install -y libicu-dev  > /dev/null
  - sudo apt-get install -y libfreetype6-dev  > /dev/null
  - sudo apt-get install -y libldap2-dev  > /dev/null
  - sudo apt-get install -y libxslt-dev  > /dev/null

  #install git & dependencies
  - sudo apt-get install -y build-essential  > /dev/null
  - sudo apt-get install g++  > /dev/null
  - sudo apt-get install -y zip  > /dev/null
  - sudo apt-get install -y autoconf  > /dev/null
  - sudo apt-get install -y libevent-pthreads-2.0-5  > /dev/null
  - sudo apt-get install -y git  > /dev/null

  # install mysql-server
  - sudo apt-get install -y mysql-server

  # install NGINX
  - sudo apt-get install -y nginx-full-dbg

  # download PHP
  - wget http://at2.php.net/get/php-7.1.3.tar.bz2/from/this/mirror >/dev/null 2>&1
  - tar -xf mirror

install:
  # Go to php installation folder
  - cd php-7.1.3

   # install PHP
  - ./configure --with-pdo-mysql --with-zlib --enable-maintainer-zts --with-curl --enable-bcmath --with-openssl --with-mysqli --enable-mbstring --with-gettext --enable-intl --with-gd --with-jpeg-dir --with-png-dir --with-freetype-dir --with-xsl --enable-sockets --enable-fpm --with-fpm-user=www-data --with-fpm-group=www-data --enable-debug --prefix=/usr/local/php --with-libdir=/lib/x86_64-linux-gnu --with-config-file-path=/usr/local/php/lib --with-config-file-scan-dir=/usr/local/php/etc/php-fpm.d
  - sudo make
  - sudo make install

  # configure php files
  - cp ./sapi/fpm/php-fpm.conf /usr/local/php/etc/php-fpm.conf
  - cp ./sapi/fpm/www.conf /usr/local/php/etc/php-fpm.d/
  - cp ./sapi/fpm/init.d.php-fpm /etc/init.d/php-fpm
  - chmod +x /etc/init.d/php-fpm

  # Go back
  - cd ..

  # run composer
  - sudo php composer.phar install

  # start php-fpm service
  - sudo service php-fpm start

  #configure NGINX
  - cp ./default /etc/nginx/sites-available/default

  #restart NGINX service
  - service nginx restart

#before_script:

script: php ./phpunit.phar --configuration ./phpunit.xml